version: '3.7'
services:
  mongodb_container:
    image: prismagraphql/mongo-single-replica:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 5
    ports:
      - 27017:27017
